### ISSUE TITLE
time.ZonedDateTime.parse and format fails with "use locale" error

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab-js#54] opened 2022-01-03 18:03 UTC
Users will frequently come into a case where they want to convert a DateTime string to a ZonedDateTime. There is a powerful parsing capability built into time.ZonedDateTime but when trying to use it I get:

```
2022-01-03 10:46:41.247 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'dads_motion' failed: org.graalvm.polyglot.PolyglotException: JsJodaException: Pattern using (localized) text not implemented, use @js-joda/locale plugin!
```

So I've tried adding to the top of my script actions:

    require('@js-joda/locale_en_us');
    require('js-joda/locale_en_us');
    require('locale_en_us');
    require('@locale_en_us');
    require('time.locale_en_us');
    require('@time.locale_en_us');

All generate a "Cannot load CommonJS module"
```
2022-01-03 10:49:25.168 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'dads_motion' failed: org.graalvm.polyglot.PolyglotException: TypeError: Cannot load CommonJS module
: 'js-joda/locale_en_us'
```

Others have reported the same problem with `locale_de` as well. As far as I can tell, at this point it's impossible to parse or format a date time string in a rule using time.ZonedDateTime without the locale imported. But I can't figure out a way to import it.

It seems like it should be imported already but can see how that might be a problem given people will want a different locale based on where they are. So I would expect that we be able to import the locale plugin as it's described in the error message, and the joda-js docs, or it be available to import through the `time` namespace or `utils` namespace. 

With the information I have right now I'm stuck.

As an aside, is it possible to use the joda-js Classes with the Java equivalents? For example, can I pass a Java ZonedDateTime to a joda-js Duration? (I know, I'll try it later but if someone knows off the top of their head...). If not, we may need to provide a function to normalize/convert from the Java to the joda-js which *should* be straight forward except for the fact that parsing Strings isn't working.

**Comment by digitaldan** [comment] 2022-01-03 18:39
Duplicate of #45 ?

**Comment by rkoshak** [comment] 2022-01-03 19:25
I'm not entirely certain. The error is different and I think the #45 fix won't work in cases where someone has some arbitrary non-ISO or RFC formatted datetime strings using locale specific names for months (for example) which I think will still fail parsing in that case.

I'll need to update the library and try it out (probably won't get to testing that until tomorrow) unless this is already part of the snapshots in which case I can confirm that it doesn't work since I'm running the latest 3.3 snapshot.

Here's the code that's failing:

```
var formatDT = function(dt) {
  //var DateTimeFormatter = Java.type("java.time.format.DateTimeFormatter");
  var formatter = time.DateTimeFormatter.ofPattern("h:mm a, ccc MMM dd");
  return dt.format(formatter);
}
```

#45 definitely solves my aside to convert a Java ZonedDateTime to js-joda though.

**Comment by digitaldan** [comment] 2022-01-03 23:16
Sorry i did not read the whole exception  message in your first post, indeed it  seems like we need to import local modules, i'll look into it.

**Comment by florian-h05** [comment] 2022-02-08 13:45
@rkoshak 
I did further inverstigation, looks like I could provide a solution in this, I will open a PR later.

**Closed** 2024-02-06 06:33 UTC
Labels: bug
