### ISSUE TITLE
Java.type("java.time.ZonedDateTime").now() and time.ZonedDateTime.now() getting different by 43sec

### ISSUE THREAD

**Issue by olili** [openhab/openhab-js#299] opened 2023-09-18 05:53 UTC
see https://community.openhab.org/t/strange-behavior-with-sw-timer-oh4/149629/22

Time provided by openhab-js  "time.ZonedDateTime.now()" and the regular java time Java.type("java.time.ZonedDateTime").now()  are getting different after time. 

Reloading the script is healing this behavior.

## Expected Behavior
times are congruent 

## Current Behavior
Java.type("java.time.ZonedDateTime").now()  is getting delayed by 43sec to Java.type("java.time.ZonedDateTime").now() 

## Possible Solution
sync times 

## Steps to Reproduce (for Bugs)
see https://community.openhab.org/t/strange-behavior-with-sw-timer-oh4/149629/22

or add following rule and watch the log file after 24h:
```javascript
configuration: {}
triggers:
  - id: "1"
    configuration:
      cronExpression: 0 0 * * * ? *
    type: timer.GenericCronTrigger
conditions: []
actions:
  - inputs: {}
    id: "3"
    configuration:
      type: application/javascript
      script: >
        var JZonedDateTime = Java.type("java.time.ZonedDateTime");


        var tmp;

        var d;


        function x1_writeFile(file, data, append) { const FileWriter = Java.type('java.io.FileWriter'); try { const output = new FileWriter(file,append);
              output.write(data);
              output.close(); }
        catch (e) { console.error(e); }}


        d = new Date( JZonedDateTime.now() );

        tmp = (['Java ZonedDateTime: ', d ,' --- OH JS ZDT: ',time.ZonedDateTime.now()].join(''));

        tmp += '\r\n';

        x1_writeFile( '/tmp/SW_Timertmp.txt', tmp, 'TRUE' === 'TRUE' ); 
    type: script.ScriptAction
```

Logs: 
`Java ZonedDateTime: Tue Sep 19 2023 20:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-19T20:00:00.067+02:00[SYSTEM]
Java ZonedDateTime: Tue Sep 19 2023 21:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-19T21:00:00.070+02:00[SYSTEM]
Java ZonedDateTime: Tue Sep 19 2023 22:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-19T22:00:00.065+02:00[SYSTEM]
Java ZonedDateTime: Tue Sep 19 2023 23:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-19T23:00:00.066+02:00[SYSTEM]
Java ZonedDateTime: Wed Sep 20 2023 00:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-20T00:00:00.068+02:00[SYSTEM]
Java ZonedDateTime: Wed Sep 20 2023 01:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-20T01:00:00.066+02:00[SYSTEM]
Java ZonedDateTime: Wed Sep 20 2023 02:00:43 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-20T02:00:00.066+02:00[SYSTEM]
Java ZonedDateTime: Wed Sep 20 2023 03:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-20T02:59:16.983+02:00[SYSTEM]
Java ZonedDateTime: Wed Sep 20 2023 04:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-20T03:59:16.984+02:00[SYSTEM]
Java ZonedDateTime: Wed Sep 20 2023 05:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-20T04:59:16.983+02:00[SYSTEM]
Java ZonedDateTime: Wed Sep 20 2023 06:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-20T05:59:16.984+02:00[SYSTEM]
Java ZonedDateTime: Wed Sep 20 2023 07:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-20T06:59:16.984+02:00[SYSTEM]
`
Update: 
delay of 43sec are logged per night!
`
Java ZonedDateTime: Wed Sep 20 2023 22:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-20T21:59:16.983+02:00[SYSTEM]
Java ZonedDateTime: Wed Sep 20 2023 23:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-20T22:59:16.984+02:00[SYSTEM]
Java ZonedDateTime: Thu Sep 21 2023 00:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-20T23:59:16.983+02:00[SYSTEM]
Java ZonedDateTime: Thu Sep 21 2023 01:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-21T00:59:16.983+02:00[SYSTEM]
Java ZonedDateTime: Thu Sep 21 2023 02:00:43 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-21T01:59:16.983+02:00[SYSTEM]
Java ZonedDateTime: Thu Sep 21 2023 03:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-21T02:58:33.908+02:00[SYSTEM]
Java ZonedDateTime: Thu Sep 21 2023 04:00:00 GMT+0200 (CEST) --- OH JS ZDT: 2023-09-21T03:58:33.910+02:00[SYSTEM]
`

## Context

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

RASPI2b, 
OH4.04

openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7)
OpenJDK Server VM Zulu17.42+19-CA (build 17.0.7+7, mixed mode)

EXTRA_JAVA_OPTS="-Xms256m -Xmx678m -XX:+ExitOnOutOfMemoryError"

**Comment by olili** [comment] 2023-09-19 16:54
description updated

**Comment by olili** [comment] 2023-11-16 17:36
problem gone with openHAB 4.0.4.

**Comment by florian-h05** [comment] 2023-11-17 07:26
Interesting, I’d say let’s close this, and in case the issue re-appears, re-open the issue (even though I have no idea how to fix that).

**Comment by olili** [comment] 2023-11-30 07:00
bad news, problem is still there. 
I was wondering why my timers for light automation are running longer as expexted and enabled the logging rule from my first post. 
And the root cause seems to be as titeled: 

Java.type("java.time.ZonedDateTime").now() and time.ZonedDateTime.now() getting different by 43sec per night:

`
Java ZonedDateTime: Mon Nov 27 2023 09:26:38 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T09:26:38.599+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 10:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T10:00:00.843+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 11:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T11:00:00.841+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 12:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T12:00:00.851+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 13:00:26 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T13:00:26.116+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 14:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T14:00:00.435+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 15:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T15:00:00.434+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 16:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T16:00:00.434+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 17:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T17:00:00.433+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 18:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T18:00:00.433+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 19:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T19:00:00.433+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 20:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T20:00:00.431+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 21:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T21:00:00.432+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 22:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T22:00:00.431+01:00[SYSTEM]
Java ZonedDateTime: Mon Nov 27 2023 23:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-27T23:00:00.432+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 00:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T00:00:00.432+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 01:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T01:00:00.434+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 02:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T02:00:43.499+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 03:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T03:00:43.497+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 04:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T04:00:43.501+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 05:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T05:00:43.499+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 06:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T06:00:43.505+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 07:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T07:00:43.498+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 08:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T08:00:43.498+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 09:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T09:00:43.499+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 10:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T10:00:43.498+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 11:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T11:00:43.498+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 12:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T12:00:43.499+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 13:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T13:00:43.498+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 14:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T14:00:43.500+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 15:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T15:00:43.498+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 16:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T16:00:43.497+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 17:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T17:00:43.497+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 18:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T18:00:43.498+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 19:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T19:00:43.498+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 20:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T20:00:43.497+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 21:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T21:00:43.499+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 22:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T22:00:43.512+01:00[SYSTEM]
Java ZonedDateTime: Tue Nov 28 2023 23:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-28T23:00:43.500+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 00:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T00:00:43.497+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 01:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T01:00:43.498+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 02:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T02:01:26.561+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 03:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T03:01:26.563+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 04:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T04:01:26.563+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 05:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T05:01:26.560+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 06:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T06:01:26.561+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 07:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T07:01:26.564+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 08:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T08:01:26.562+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 09:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T09:01:26.560+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 10:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T10:01:26.560+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 11:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T11:01:26.559+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 12:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T12:01:26.559+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 13:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T13:01:26.560+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 14:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T14:01:26.559+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 15:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T15:01:26.566+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 16:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T16:01:26.561+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 17:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T17:01:26.559+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 18:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T18:01:26.559+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 19:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T19:01:26.559+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 20:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T20:01:26.561+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 21:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T21:01:26.558+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 22:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T22:01:26.560+01:00[SYSTEM]
Java ZonedDateTime: Wed Nov 29 2023 23:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-29T23:01:26.568+01:00[SYSTEM]
Java ZonedDateTime: Thu Nov 30 2023 00:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-30T00:01:26.560+01:00[SYSTEM]
Java ZonedDateTime: Thu Nov 30 2023 01:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-30T01:01:26.558+01:00[SYSTEM]
Java ZonedDateTime: Thu Nov 30 2023 02:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-30T02:02:09.631+01:00[SYSTEM]
Java ZonedDateTime: Thu Nov 30 2023 03:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-30T03:02:09.632+01:00[SYSTEM]
Java ZonedDateTime: Thu Nov 30 2023 04:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-30T04:02:09.632+01:00[SYSTEM]
Java ZonedDateTime: Thu Nov 30 2023 05:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-30T05:02:09.632+01:00[SYSTEM]
Java ZonedDateTime: Thu Nov 30 2023 06:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-30T06:02:09.633+01:00[SYSTEM]
Java ZonedDateTime: Thu Nov 30 2023 07:00:00 GMT+0100 (CET) --- OH JS ZDT: 2023-11-30T07:02:09.631+01:00[SYSTEM]
`

**Comment by florian-h05** [comment] 2023-11-30 07:04
Can you please share your rule code?

BTW: Please use code blocks for your logs, not the code enclosing stuff: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by olili** [comment] 2023-11-30 07:08
my rule is attached within correct "code blocks" in my intial post of this this thread. 

Sorry, for using the wrong meta characters....

**Comment by florian-h05** [comment] 2023-12-06 07:24
Sorry for not seeing the rule code at the top.

I will try to reproduce this on my machine. If I can reproduce this, I guess we can't really fix it, because it is either a problem with JS-Joda and/or GraalJS, but we probably are able to work around it.

**Comment by olili** [comment] 2023-12-25 07:32
issue has not gone with oh4.1 - still 43sec per night.
Somebody else facing this issue as well?
Any idea where it comes from? 

O.

**Comment by olili** [comment] 2024-01-29 14:28
I finally found the root cause and a solution.

I'm using DietPi for RaspberryPi.
System clock was configured to be synced once per day at 01.17AM. 
During day system clock is drifting by 43sec in my case. 

Running scripts/rules in OH4 are excluded from this single update of system clock (why is still not clear for me... ). 

Solution: 
DietPI is offering also a timesync daemon that is continously adjusting system time.
Enabling this feature resolved my issue. 

Best regards,
Oliver

**Comment by florian-h05** [comment] 2024-01-29 15:12
Hmm, okay thanks for the information.

**Closed by florian-h05** 2024-01-29 15:12 UTC
Labels: bug
